const tempSearch = [
  {
    adult: false,
    backdrop_path: "/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg",
    genre_ids: [18],
    id: 550,
    original_language: "en",
    original_title: "Fight Club",
    overview:
      'A ticking-time-bomb insomniac and a slippery sjdhflkjshdfkljsdhfkjdshfksdjhsldkhlskdjflsjdhsdjhflskdjfsdhflkjsdfljsdhflsdjhfldsk jhsfjhsdl jsdlkfj hsdjfhsdlf jhsdkfjhsdl jhsdlkfjshdl fjshdlfjhsd fkjsdh sdjhf lksd jhflksjhsdlk jhslkdjhfl ksjd hflksd jhldskjsoap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    popularity: 76.759,
    poster_path: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    release_date: "1999-10-15",
    title: "Fight Club",
    video: false,
    vote_average: 8.4,
    vote_count: 24535,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 883656,
    original_language: "en",
    original_title: "GCW Fight Club",
    overview:
      'A ticking-time-bomb insomniac and a slippery sjdhflkjshdfkljsdhfkjdshfksdjhsldkhlskdjflsjdhsdjhflskdjfsdhflkjsdfljsdhflsdjhfldsk jhsfjhsdl jsdlkfj hsdjfhsdlf jhsdkfjhsdl jhsdlkfjshdl fjshdlfjhsd fkjsdh sdjhf lksd jhflksjhsdlk jhslkdjhfl ksjd hflksd jhldskjsoap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    popularity: 3.625,
    poster_path: "/a9RWdhRLyx3BqCjlwmZJHXyeMkR.jpg",
    release_date: "2021-10-09",
    title: "GCW Fight Club",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28],
    id: 347807,
    original_language: "hi",
    original_title: "Fight Club: Members Only",
    overview:
      'A ticking-time-bomb insomniac and a slippery sjdhflkjshdfkljsdhfkjdshfksdjhsldkhlskdjflsjdhsdjhflskdjfsdhflkjsdfljsdhflsdjhfldsk jhsfjhsdl jsdlkfj hsdjfhsdlf jhsdkfjhsdl jhsdlkfjshdl fjshdlfjhsd fkjsdh sdjhf lksd jhflksjhsdlk jhslkdjhfl ksjd hflksd jhldskjsoap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    popularity: 2.307,
    poster_path: "/aXFmWfWYCCxQTkCn7K86RvDiMHZ.jpg",
    release_date: "2006-02-17",
    title: "Fight Club: Members Only",
    video: false,
    vote_average: 3.4,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 289100,
    original_language: "en",
    original_title: "Girls Fight Club",
    overview:
      'A ticking-time-bomb insomniac and a slippery sjdhflkjshdfkljsdhfkjdshfksdjhsldkhlskdjflsjdhsdjhflskdjfsdhflkjsdfljsdhflsdjhfldsk jhsfjhsdl jsdlkfj hsdjfhsdlf jhsdkfjhsdl jhsdlkfjshdl fjshdlfjhsd fkjsdh sdjhf lksd jhflksjhsdlk jhslkdjhfl ksjd hflksd jhldskjsoap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    popularity: 0.954,
    poster_path: null,
    release_date: "2009-06-18",
    title: "Girls Fight Club",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
];

export default tempSearch;
